// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/Mekawy5/chatapp/controller"
	"github.com/Mekawy5/chatapp/domain/application"
	"github.com/Mekawy5/chatapp/domain/chat"
	"github.com/Mekawy5/chatapp/domain/message"
	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitApplicationController(db *gorm.DB, srv *gin.Engine) *controller.ApplicationController {
	applicationRepository := application.NewApplicationRepository(db)
	applicationService := application.NewApplicationService(applicationRepository)
	applicationController := controller.NewApplicationController(srv, applicationService)
	return applicationController
}

func InitChatController(db *gorm.DB, srv *gin.Engine) *controller.ChatController {
	chatRepository := chat.NewChatRepository(db)
	chatService := chat.NewChatService(chatRepository)
	chatController := controller.NewChatController(srv, chatService)
	return chatController
}

func InitMessageController(db *gorm.DB, srv *gin.Engine) *controller.MessageController {
	messageRepository := message.NewMessageRepository(db)
	messageService := message.NewMessageService(messageRepository)
	messageController := controller.NewMessageController(srv, messageService)
	return messageController
}
